version: '3.8'

services:
  database:
    image: "postgres:13-alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "9998:5432"

  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "9999:8000"
#    volumes:
#      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal